default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'aishadoite91' } %>
  host: localhost

development:
  <<: *default
  database: rakusuru_development

test:
  <<: *default
  database: rakusuru_test

production:
  <<: *default
  database: rakusuru_production
  username: rakusuru
  password: <%= ENV['RAKUSURU_DATABASE_PASSWORD'] %>
